service: ${env:SERVICE_NAME}

frameworkVersion: "3"

provider:
  name: aws
  runtime: go1.x

  stage: ${env:STAGE}
  region: ${env:AWS_REGION}

  deploymentBucket:
    name: "sls-deployment-bucket-${env:SERVICE_NAME}-${env:STAGE}"
    serverSideEncryption: AES256

  logRetentionInDays: 1

  environment:
    INVOKED_FUNCTION_NAME: ${env:INVOKED_FUNCTION_NAME}
    SLACK_ACCESS_TOKEN: ${env:SLACK_ACCESS_TOKEN}
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_VERIFICATION_TOKEN: ${env:SLACK_VERIFICATION_TOKEN}

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "lambda:InvokeFunction"
          Resource:
            - ${env:AWS_RESOURCE}

  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedHeaders:
        - Content-Type
        - Authorization

custom:
  deploymentBucket:
    blockPublicAccess: true

package:
  patterns:
    - "!./**"
    - ./bin/**

plugins:
  - serverless-deployment-bucket

functions:
  eventReceiver:
    handler: bin/event/receiver
    events:
      - httpApi:
          path: /event/receiver
          method: post
  eventAction:
    handler: bin/event/action
